version: '3.8'

services:
  neo4j:
    image: neo4j:5.22.0-community
    container_name: neo4j_db
    restart: always
    environment:
      NEO4J_AUTH: "neo4j/supersecurepassword"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  flask_api:
    build: .
    container_name: flask_api
    restart: always
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: "bolt://neo4j_db:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "supersecurepassword"
      FLASK_ENV: "production"
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  neo4j_data:
    driver: local
